name: meu-desafio
services:
  react: 
    build: ./app-desafio
    ports: 
      - 5173:5173
    volumes:
      - ./app-desafio:/app
      - /app/node_modules
  
  express: 
    build: ./api
    ports: 
     - 8081:3000
    volumes:
      - ./api:/api
      - /api/node_modules
    environment:
      NODE_ENV: development
      DB_HOST: postgresql
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}
      DB_PORT: 5432
    depends_on:
    - postgresql

  postgresql:
    image: postgres
    ports: 
      - 5432:5432
    volumes: 
      - pg_data:/var/lib/postgresql/data
      - ./init_script_db:/docker-entrypoint-initdb.d
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_DB: ${POSTGRES_DB} 
    

volumes:
  pg_data:
   
